[project]
name = "shenji_training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "python-chess>=1.999",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
    "tensorboard>=2.20",
    "zstandard>=0.23.0",
    "pyyaml>=6.0.2",
    "black>=25.1.0",
    "isort>=6.0.1",
]
